version: '3.7'

services:
  hugo_server:
    image: klakegg/hugo:0.74.3
    command: server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"

  build:
    image: klakegg/hugo:0.74.3
    volumes:
      - ".:/src"
