name: Hugo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Create /docs directory
        run: |
          rm -rf ${{ github.workspace }}/docs
          mkdir ${{ github.workspace }}/docs

      - name: Build and Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.BUILD_TOKEN }}
          args: --gc --minify --cleanDestinationDir --destination=${{ github.workspace }}/docs/ --verbose=true --debug
          branch: master
